BMS_CAN_MONITOR_VERSION = 1.0
BMS_CAN_MONITOR_SITE = $(BR2_EXTERNAL_BMS_PATH)/../kernel
BMS_CAN_MONITOR_SITE_METHOD = local
BMS_CAN_MONITOR_MODULE_MAKE_OPTS = KDIR=$(LINUX_DIR)
BMS_CAN_MONITOR_MODULE_SUBDIRS = .

$(eval $(kernel-module))
$(eval $(generic-package))

