BMS_GATEWAY_VERSION = 1.0
BMS_GATEWAY_SITE = $(BR2_EXTERNAL_BMS_PATH)/../userspace
BMS_GATEWAY_SITE_METHOD = local

define BMS_GATEWAY_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D)
endef

define BMS_GATEWAY_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) DESTDIR=$(TARGET_DIR) -C $(@D) install
endef

$(eval $(generic-package))

